MODEL: two-pass
DROPOUT_RNN: 0.1
RNN_HIDDEN_SIZE: 512
RNN_LAYER: 2
CTRL_LAYER: 1
CTRL_HIDDEN_SIZE: 512
REV_OFFSET: 0
CACHE_SIZE: 3
RNN_TYPE: LSTM

# Non-incremental model
REVISER: transformers
LAYER: 1
HIDDEN_SIZE: 512
ATTENTION_HEAD: 8
DROPOUT: 0.1
FF_SIZE: 2048
REVISER_CKPT_PATH: null
REVISER_CKPT_VERSION: two_pass_reviser
REVISER_CKPT_EPOCH: 18

# Execution
BATCH_SIZE: 128
LR: 0.0001
MAX_EPOCH: 50
GRAD_CLIP: 1
DELAY: 0
ACCU_GRAD: 1
UNK_PROB: 0.02
LR_DECAY_LIST: [50]
LR_DECAY_RATE: 1
WARMUP_EPOCH: 5
OPT: AdamW
OPT_PARAMS: {betas: '(0.9, 0.98)', eps: '1e-9'}